on:
  workflow_dispatch:
  pull_request:
  push:

name: Build

concurrency:
  group: ${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build R from SVN mirror
    uses: r-devel/actions/.github/workflows/build-svn.yaml@main
